# Data extraction and transformation

Установим все необходимые библиотеки

In [2]:
%pip install -r requirements.txt

Requirement already satisfied: contourpy==1.3.3 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: cycler==0.12.1 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: fonttools==4.62.1 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 3)) (4.62.1)
Requirement already satisfied: kiwisolver==1.5.0 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: matplotlib==3.10.8 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 5)) (3.10.8)
Requirement already satisfied: numpy==2.4.4 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 6)) (2.4.4)
Requirement already satisfied: packaging==26.0 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 7)) (26.0)
Requirement already satisfied: pandas==3.0.2 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 8)) (3.0.2)
Requirement already satisfied: pillow==12.2.0 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 9)) (12.2.0)
Requirement already satisfied: pyparsing==3.3.2 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 10)) (3.3.2)
Requirement already satisfied: python-dateutil==2.9.0.post0 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 11)) (2.9.0.post0)
Requirement already satisfied: seaborn==0.13.2 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 12)) (0.13.2)
Requirement already satisfied: six==1.17.0 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 13)) (1.17.0)
Requirement already satisfied: tzdata==2026.1 in c:\Users\Aleksandr Riabkov\Desktop\Itmo.py\ITMO.py\second_semester\LR5. Scikit-learn. Regression\venv\Lib\site-packages (from -r requirements.txt (line 14)) (2026.1)
Note: you may need to restart the kernel to use updated packages.

In [10]:
# Импорт всех модулей
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import scipy as sp

In [11]:
# Настройки
pd.set_option('display.max_columns', None)
sns.set_theme(style='whitegrid', palette='Set2')
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12

## EDA

In [13]:
# Импорт данных

df = pd.read_csv('data/titanic_dataset.csv')

df.head(10)
# df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [26]:
# Проверка типов данных каждого столбца
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [ ]:
# Проверка общей информации и типов данных колонок
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [57]:
# статистика по пустым столбцам

blanks_statistics = pd.DataFrame({
    'Всего': df.isna().sum(),
    'Процент пропущенных пробелов': (df.isna().sum() / df.shape[0] * 100)
})   

blanks_statistics.sort_values(by='Процент пропущенных пробелов', ascending=False)

             Всего  Процент пропущенных пробелов
Cabin          687                     77.104377
Age            177                     19.865320
Embarked         2                      0.224467
PassengerId      0                      0.000000
Name             0                      0.000000
Pclass           0                      0.000000
Survived         0                      0.000000
Sex              0                      0.000000
Parch            0                      0.000000
SibSp            0                      0.000000
Fare             0                      0.000000
Ticket           0                      0.000000

In [62]:
(df.isna().sum() / df.shape[0] * 100).values

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       19.86531987,  0.        ,  0.        ,  0.        ,  0.        ,
       77.1043771 ,  0.22446689])

In [23]:
# статистическая информация про каждый числовой столбец
df.describe().T

,count,mean,std,min,25%,50%,75%,max
PassengerId,891.0,446.000000,257.353842,1.00,223.5000,446.0000,668.5,891.0000
Survived,891.0,0.383838,0.486592,0.00,0.0000,0.0000,1.0,1.0000
Pclass,891.0,2.308642,0.836071,1.00,2.0000,3.0000,3.0,3.0000
Age,714.0,29.699118,14.526497,0.42,20.1250,28.0000,38.0,80.0000
SibSp,891.0,0.523008,1.102743,0.00,0.0000,0.0000,1.0,8.0000
Parch,891.0,0.381594,0.806057,0.00,0.0000,0.0000,0.0,6.0000
Fare,891.0,32.204208,49.693429,0.00,7.9104,14.4542,31.0,512.3292

In [ ]:
# гистограммы распределения числовых признаков

## Filling blanks

winsorisation:
    
pandas - quantile
scipy - winsorise